# revision 31970
# category Package
# catalog-ctan /fonts/sourcesanspro
# catalog-date 2013-05-02 20:50:09 +0200
# catalog-license ofl
# catalog-version 2.2
Name:		texlive-sourcesanspro
Version:	2.2
Release:	10
Summary:	Use SourceSansPro with TeX(-alike) systems
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/fonts/sourcesanspro
License:	OFL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/sourcesanspro.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/sourcesanspro.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
The font is an open-source Sans-Serif development from Adobe.
The package provides fonts (in both Adobe Type 1 and OpenType
formats) and macros supporting their use in LaTeX (Type 1) and
XeLaTeX/LuaLaTeX (OTF).

%post
    %{_sbindir}/texlive.post

%postun
    if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_2cvp4u.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_3rlax2.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_5tbsmu.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_6bttxp.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_b457hn.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_emm5ci.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_fva737.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_gvadt4.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_kksgzp.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_ko3vnf.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_kxwkma.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_p5cgg3.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_psnyba.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_x5hjjp.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_xfkmtv.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_yugc2g.enc
%{_texmfdistdir}/fonts/enc/dvips/sourcesanspro/a_zd345j.enc
%{_texmfdistdir}/fonts/map/dvips/sourcesanspro/SourceSansPro.map
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-Black.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-BlackIt.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-Bold.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-BoldIt.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-ExtraLight.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-ExtraLightIt.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-Light.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-LightIt.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-Regular.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-RegularIt.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-Semibold.otf
%{_texmfdistdir}/fonts/opentype/adobe/sourcesanspro/SourceSansPro-SemiboldIt.otf
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Black-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BlackIt-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Bold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-BoldIt-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-It-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Light-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-LightIt-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Regular-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-sc-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-sc-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-sc-ot1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-sc-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-sc-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-sc-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tosf-ts1.tfm
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-Black.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-BlackIt.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-Bold.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-BoldIt.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-ExtraLight.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-ExtraLightIt.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-It.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-Light.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-LightIt.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-Regular.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-Semibold.pfb
%{_texmfdistdir}/fonts/type1/adobe/sourcesanspro/SourceSansPro-SemiboldIt.pfb
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Black-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BlackIt-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Bold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-BoldIt-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLight-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-ExtraLightIt-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-It-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Light-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-LightIt-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Regular-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-lf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-lf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-lf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-osf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-osf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-osf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-sc-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-sc-ot1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-sc-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-Semibold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-lf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-osf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/adobe/sourcesanspro/SourceSansPro-SemiboldIt-tosf-ts1.vf
%{_texmfdistdir}/tex/latex/sourcesanspro/LY1SourceSansPro-LF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/LY1SourceSansPro-OsF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/LY1SourceSansPro-TLF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/LY1SourceSansPro-TOsF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/OT1SourceSansPro-LF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/OT1SourceSansPro-OsF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/OT1SourceSansPro-TLF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/OT1SourceSansPro-TOsF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/T1SourceSansPro-LF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/T1SourceSansPro-OsF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/T1SourceSansPro-TLF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/T1SourceSansPro-TOsF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/TS1SourceSansPro-LF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/TS1SourceSansPro-OsF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/TS1SourceSansPro-TLF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/TS1SourceSansPro-TOsF.fd
%{_texmfdistdir}/tex/latex/sourcesanspro/sourcesanspro-type1-autoinst.sty
%{_texmfdistdir}/tex/latex/sourcesanspro/sourcesanspro.sty
%doc %{_texmfdistdir}/doc/latex/sourcesanspro/LICENSE.txt
%doc %{_texmfdistdir}/doc/latex/sourcesanspro/README
%doc %{_texmfdistdir}/doc/latex/sourcesanspro/sourcesanspro-otf-specimen.pdf
%doc %{_texmfdistdir}/doc/latex/sourcesanspro/sourcesanspro-otf-specimen.tex
%doc %{_texmfdistdir}/doc/latex/sourcesanspro/sourcesanspro-type1-specimen.pdf
%doc %{_texmfdistdir}/doc/latex/sourcesanspro/sourcesanspro-type1-specimen.tex
%doc %{_texmfdistdir}/doc/latex/sourcesanspro/sourcesanspro.pdf
%doc %{_texmfdistdir}/doc/latex/sourcesanspro/sourcesanspro.tex

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar fonts tex doc %{buildroot}%{_texmfdistdir}
